server:
  port: 8401 #端口
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: sentinel-service #服务名
  cloud:
    nacos:
      discovery:
        #Nacos服务注册中心(集群)地址
        server-addr: localhost:8848

    sentinel:
      transport:
        #配置 Sentinel dashboard 地址
        dashboard: localhost:8858
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
        clientIp: 172.20.10.4

      filter:
        url-patterns: /**

management:
  endpoints:
    web:
      exposure:
        include: '*'